In [8]:
import numpy as np
a = np.array([1,2,3])
a = np.expand_dims(a, axis=0)

b = np.array([4,5,6])
b = np.expand_dims(b, axis=0)
print(a,b)
np.concatenate([a,b], axis=1)

[[1 2 3]] [[4 5 6]]


array([[1, 2, 3, 4, 5, 6]])

In [9]:
type(np.floor(2000/1000))
print(np.array(1000).shape)
print(np.array([1000]).shape)

()
(1,)


In [10]:
import my_hdqn_learning
import agents.my_hdqn_agent
import envs.tetris

num_rows, num_cols = 4, 4
env = envs.tetris.Tetris(num_rows, num_cols)
initial_state, _ = env.reset()


In [12]:
import random
import torch
random.randrange(2)

zeros = np.zeros(3)
torch.tensor(zeros)

tensor([0., 0., 0.], dtype=torch.float64)